apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-maven
  name: my-maven
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-maven
status:
  loadBalancer: {}
